// <auto-generated />
using System;
using Gamificacao.Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gamificacao.Api.Migrations
{
    [DbContext(typeof(GamificacaoDbContext))]
    [Migration("20260709193502_AdicionaSequenciaUsuarioEExpandeConquistas")]
    partial class AdicionaSequenciaUsuarioEExpandeConquistas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gamificacao.Api.Dominio.Conquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Conquistas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = "PRIMEIRO_SALARIO",
                            Descricao = "Registrou seu primeiro lançamento de salário.",
                            Icone = "cash-outline",
                            Nome = "Primeiro salário"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = "LANCAMENTOS_10",
                            Descricao = "Registrou 10 lançamentos no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "10 lançamentos"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Codigo = "LANCAMENTOS_100",
                            Descricao = "Registrou 100 lançamentos no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "100 lançamentos"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Codigo = "LANCAMENTOS_1000",
                            Descricao = "Registrou 1000 lançamentos no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "1000 lançamentos"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Codigo = "PRIMEIRA_META_CONCLUIDA",
                            Descricao = "Concluiu sua primeira meta de poupança.",
                            Icone = "trophy-outline",
                            Nome = "Primeira meta concluída"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Codigo = "METAS_CONCLUIDAS_5",
                            Descricao = "Concluiu 5 metas de poupança.",
                            Icone = "trophy-outline",
                            Nome = "5 metas concluídas"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Codigo = "SEQUENCIA_7",
                            Descricao = "Usou o Cofrin por 7 dias seguidos.",
                            Icone = "flame-outline",
                            Nome = "7 dias de sequência"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Codigo = "SEQUENCIA_30",
                            Descricao = "Usou o Cofrin por 30 dias seguidos.",
                            Icone = "flame-outline",
                            Nome = "30 dias de sequência"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Codigo = "SEQUENCIA_100",
                            Descricao = "Usou o Cofrin por 100 dias seguidos.",
                            Icone = "flame-outline",
                            Nome = "100 dias de sequência"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Codigo = "SEQUENCIA_365",
                            Descricao = "Usou o Cofrin por 365 dias seguidos.",
                            Icone = "flame-outline",
                            Nome = "365 dias de sequência"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Codigo = "LANCAMENTOS_1",
                            Descricao = "Registrou seu primeiro lançamento no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "Primeiro lançamento"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Codigo = "LANCAMENTOS_50",
                            Descricao = "Registrou 50 lançamentos no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "50 lançamentos"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Codigo = "LANCAMENTOS_500",
                            Descricao = "Registrou 500 lançamentos no Cofrin.",
                            Icone = "receipt-outline",
                            Nome = "500 lançamentos"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Codigo = "METAS_CONCLUIDAS_10",
                            Descricao = "Concluiu 10 metas de poupança.",
                            Icone = "trophy-outline",
                            Nome = "10 metas concluídas"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Codigo = "METAS_CONCLUIDAS_25",
                            Descricao = "Concluiu 25 metas de poupança.",
                            Icone = "trophy-outline",
                            Nome = "25 metas concluídas"
                        });
                });

            modelBuilder.Entity("Gamificacao.Api.Dominio.ContadorConquista", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "Chave");

                    b.ToTable("ContadoresConquista", (string)null);
                });

            modelBuilder.Entity("Gamificacao.Api.Dominio.MovimentoMoedas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimentosMoedas", (string)null);
                });

            modelBuilder.Entity("Gamificacao.Api.Dominio.Resgate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Resgates", (string)null);
                });

            modelBuilder.Entity("Gamificacao.Api.Dominio.SequenciaUsuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("MelhorSequencia")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("UltimoDiaContado")
                        .HasColumnType("date");

                    b.HasKey("UsuarioId");

                    b.ToTable("SequenciasUsuario", (string)null);
                });

            modelBuilder.Entity("Gamificacao.Api.Dominio.UsuarioConquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConquistaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DesbloqueadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "ConquistaId")
                        .IsUnique();

                    b.ToTable("UsuariosConquistas", (string)null);
                });

            modelBuilder.Entity("Gamificacao.Api.Persistencia.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessadoEm");

                    b.ToTable("OutboxMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
